name: Docker Image CI

on:
  push:
    branches: [ master, release/* ]
    branches-ignore: [develop]
  pull_request:
    branches: [ master, release/* ]

jobs:

  build:

    runs-on: ubuntu-20.04, ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
